
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Solicitudes extends javax.swing.JFrame {

    /**
     * Creates new form Solicitudes
     */
    public Solicitudes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Cola micola = new Cola();
    Clientes client = new Clientes();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CedulaSolicitud = new javax.swing.JTextField();
        MarcaSolicitud = new javax.swing.JTextField();
        ModeloSolicitud = new javax.swing.JTextField();
        PasajerosSolicitud = new javax.swing.JTextField();
        DiasSolicitud = new javax.swing.JTextField();
        FechaSolicitud = new javax.swing.JTextField();
        SinLlave = new javax.swing.JCheckBox();
        Cargador = new javax.swing.JCheckBox();
        Sensores = new javax.swing.JCheckBox();
        GPS = new javax.swing.JCheckBox();
        CrearSolicitud = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cedula");

        jLabel2.setText("Fecha");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("Pasajeros");

        jLabel6.setText("Dias");

        jLabel7.setText("Extras");

        ModeloSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloSolicitudActionPerformed(evt);
            }
        });

        SinLlave.setText("Arranque sin llave");

        Cargador.setText("Cargador Inalambrico");

        Sensores.setText("Sensores + Camara reversa");

        GPS.setText("GPS - Navegador en tiempo real");

        CrearSolicitud.setText("Crear Solicitud");
        CrearSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearSolicitudActionPerformed(evt);
            }
        });

        jLabel8.setText("Solicitudes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MarcaSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(ModeloSolicitud)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CedulaSolicitud, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(FechaSolicitud)
                            .addComponent(PasajerosSolicitud)
                            .addComponent(DiasSolicitud))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SinLlave)
                        .addGap(92, 92, 92))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cargador)
                            .addComponent(GPS)
                            .addComponent(Sensores))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(197, 197, 197))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(CrearSolicitud))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(CedulaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(SinLlave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Cargador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(MarcaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(ModeloSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(PasajerosSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(DiasSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GPS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sensores))))
                    .addComponent(FechaSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(CrearSolicitud)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModeloSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloSolicitudActionPerformed

    private void CrearSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearSolicitudActionPerformed
        int Cedula = Integer.parseInt(CedulaSolicitud.getText());
       System.out.println(Cedula);
       String Fecha = FechaSolicitud.getText();
       String Estado = "Registrada";
       String Marca = MarcaSolicitud.getText();
       int Pasajeros = Integer.parseInt(PasajerosSolicitud.getText());
       int Dias = Integer.parseInt(DiasSolicitud.getText());
       String Modelo = ModeloSolicitud.getText();
       double iva = (Dias*15000)*0.13;
       double alquiler = (Dias*15000) + iva;
       //System.out.println(client.mipila.search1(Cedula));
       if(client.mipila.search(Cedula)){
           String Categoria = client.mipila.mostrarCategoria(Cedula);
           if(SinLlave.isSelected()){
                String Extras = "Arranque sin llave";
                micola.encola(new Solicitud(Cedula,Fecha,Dias,
               Estado,Pasajeros,Marca,Modelo,
               Extras,Categoria,alquiler));
                SubirCategoria(Cedula,Categoria,alquiler);
            }else if(Cargador.isSelected()){
                String Extras = "Cargador Inalambrico";
                micola.encola(new Solicitud(Cedula,Fecha,Dias,
               Estado,Pasajeros,Marca,Modelo,
               Extras,Categoria,alquiler));
                SubirCategoria(Cedula,Categoria,alquiler);
            }else if(GPS.isSelected()){
                String Extras = "GPS - Navegador en tiempo real";
                micola.encola(new Solicitud(Cedula,Fecha,Dias,
               Estado,Pasajeros,Marca,Modelo,
               Extras,Categoria,alquiler));
                SubirCategoria(Cedula,Categoria,alquiler);
            }else{
                String Extras = "Sensores + Camara reversa";
                micola.encola(new Solicitud(Cedula,Fecha,Dias,
               Estado,Pasajeros,Marca,Modelo,
               Extras,Categoria,alquiler));
                SubirCategoria(Cedula,Categoria,alquiler);
            }
           JOptionPane.showMessageDialog(null,"Solicitud "
                + "registrada exitosamente");
        }else{
           JOptionPane.showMessageDialog(null,
                   "Usuario no existe");
       }
       limpiarSolicitudes(); 
    }//GEN-LAST:event_CrearSolicitudActionPerformed
    private void SubirCategoria(int Cedula,String Categoria,double precio){
        if(precio > 70000){
            if(Categoria == "Oro"){
                client.mipila.SubirCategoria(Cedula,"Zafiro");
                micola.SubirCategoria(Cedula, "Zafiro");
            }else if(Categoria == "Plata"){
                client.mipila.SubirCategoria(Cedula,"Oro");
                micola.SubirCategoria(Cedula, "Oro");
            }else if(Categoria == "Bronce"){
                client.mipila.SubirCategoria(Cedula,"Plata");
                micola.SubirCategoria(Cedula, "Plata");
            }else{
                JOptionPane.showMessageDialog(null,
                   "Ya tienes la Categoria maxima");
            }
        }
    }
    
    private void limpiarSolicitudes(){
        //Limpiar todos los campos
        CedulaSolicitud.setText("");
        MarcaSolicitud.setText("");
        FechaSolicitud.setText("");
        ModeloSolicitud.setText("");
        PasajerosSolicitud.setText("");
        DiasSolicitud.setText("");
        GPS.setSelected(false);
        Cargador.setSelected(false);
        SinLlave.setSelected(false);
        Sensores.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solicitudes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Cargador;
    private javax.swing.JTextField CedulaSolicitud;
    private javax.swing.JButton CrearSolicitud;
    private javax.swing.JTextField DiasSolicitud;
    private javax.swing.JTextField FechaSolicitud;
    private javax.swing.JCheckBox GPS;
    private javax.swing.JTextField MarcaSolicitud;
    private javax.swing.JTextField ModeloSolicitud;
    private javax.swing.JTextField PasajerosSolicitud;
    private javax.swing.JCheckBox Sensores;
    private javax.swing.JCheckBox SinLlave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
